# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter自动化构建

# 触发时机
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v1

      - name: 配置java环境
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: 配置flutter环境
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'
          cache: true

      - name: 缓存gradle
        run: mkdir -p ~/.gradle/caches ~/.gradle/wrapper/
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: 更新依赖
        run: flutter pub get

      - name: 提取版本号
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: 分包构建
        run: flutter build apk --release --target-platform android-arm64,android-arm --split-per-abi

      - name: 创建发布
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{secrets.TOKEN}}
          tag: "v${{env.APP_VERSION}}-build${{github.run_number}}"
