name: 自动推送到pub.dev仓库

# 触发时机
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v3 

      - name: 配置flutter环境
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'
          cache: true

      - name: 更新依赖
        run: flutter pub get

      - name: 推送到pub.dev仓库
        run: flutter pub publish --server=https://pub.dartlang.org --force
        # env:
        #   PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        # run: |
        #   echo $PUB_DEV_TOKEN > ~/.pub-cache/credentials.json
        #   flutter pub publish --server=https://pub.dartlang.org --force
